/*
 * Etsy Open API v3
 * <div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace <a class=\"wt-text-link wt-p-xs-0\" href=\"https://www.etsy.com/developers/documentation\">Etsy's Open API v2</a>, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/issues/new/choose\">please add an issue in Github</a>.</p></div>&copy; 2021-2022 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: developers@etsy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PaymentAdjustment
 */
public class PaymentAdjustmentTest {
    private final PaymentAdjustment model = new PaymentAdjustment();

    /**
     * Model tests for PaymentAdjustment
     */
    @Test
    public void testPaymentAdjustment() {
        // TODO: test PaymentAdjustment
    }

    /**
     * Test the property 'paymentAdjustmentId'
     */
    @Test
    public void paymentAdjustmentIdTest() {
        // TODO: test paymentAdjustmentId
    }

    /**
     * Test the property 'paymentId'
     */
    @Test
    public void paymentIdTest() {
        // TODO: test paymentId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'isSuccess'
     */
    @Test
    public void isSuccessTest() {
        // TODO: test isSuccess
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'reasonCode'
     */
    @Test
    public void reasonCodeTest() {
        // TODO: test reasonCode
    }

    /**
     * Test the property 'totalAdjustmentAmount'
     */
    @Test
    public void totalAdjustmentAmountTest() {
        // TODO: test totalAdjustmentAmount
    }

    /**
     * Test the property 'shopTotalAdjustmentAmount'
     */
    @Test
    public void shopTotalAdjustmentAmountTest() {
        // TODO: test shopTotalAdjustmentAmount
    }

    /**
     * Test the property 'buyerTotalAdjustmentAmount'
     */
    @Test
    public void buyerTotalAdjustmentAmountTest() {
        // TODO: test buyerTotalAdjustmentAmount
    }

    /**
     * Test the property 'totalFeeAdjustmentAmount'
     */
    @Test
    public void totalFeeAdjustmentAmountTest() {
        // TODO: test totalFeeAdjustmentAmount
    }

    /**
     * Test the property 'createTimestamp'
     */
    @Test
    public void createTimestampTest() {
        // TODO: test createTimestamp
    }

    /**
     * Test the property 'updateTimestamp'
     */
    @Test
    public void updateTimestampTest() {
        // TODO: test updateTimestamp
    }

}
