/*
 * Etsy Open API v3
 * <div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace <a class=\"wt-text-link wt-p-xs-0\" href=\"https://www.etsy.com/developers/documentation\">Etsy's Open API v2</a>, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/issues/new/choose\">please add an issue in Github</a>.</p></div>&copy; 2021-2022 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: developers@etsy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Shop
 */
public class ShopTest {
    private final Shop model = new Shop();

    /**
     * Model tests for Shop
     */
    @Test
    public void testShop() {
        // TODO: test Shop
    }

    /**
     * Test the property 'shopId'
     */
    @Test
    public void shopIdTest() {
        // TODO: test shopId
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'shopName'
     */
    @Test
    public void shopNameTest() {
        // TODO: test shopName
    }

    /**
     * Test the property 'createDate'
     */
    @Test
    public void createDateTest() {
        // TODO: test createDate
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'announcement'
     */
    @Test
    public void announcementTest() {
        // TODO: test announcement
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    public void currencyCodeTest() {
        // TODO: test currencyCode
    }

    /**
     * Test the property 'isVacation'
     */
    @Test
    public void isVacationTest() {
        // TODO: test isVacation
    }

    /**
     * Test the property 'vacationMessage'
     */
    @Test
    public void vacationMessageTest() {
        // TODO: test vacationMessage
    }

    /**
     * Test the property 'saleMessage'
     */
    @Test
    public void saleMessageTest() {
        // TODO: test saleMessage
    }

    /**
     * Test the property 'digitalSaleMessage'
     */
    @Test
    public void digitalSaleMessageTest() {
        // TODO: test digitalSaleMessage
    }

    /**
     * Test the property 'updateDate'
     */
    @Test
    public void updateDateTest() {
        // TODO: test updateDate
    }

    /**
     * Test the property 'listingActiveCount'
     */
    @Test
    public void listingActiveCountTest() {
        // TODO: test listingActiveCount
    }

    /**
     * Test the property 'digitalListingCount'
     */
    @Test
    public void digitalListingCountTest() {
        // TODO: test digitalListingCount
    }

    /**
     * Test the property 'loginName'
     */
    @Test
    public void loginNameTest() {
        // TODO: test loginName
    }

    /**
     * Test the property 'acceptsCustomRequests'
     */
    @Test
    public void acceptsCustomRequestsTest() {
        // TODO: test acceptsCustomRequests
    }

    /**
     * Test the property 'policyWelcome'
     */
    @Test
    public void policyWelcomeTest() {
        // TODO: test policyWelcome
    }

    /**
     * Test the property 'policyPayment'
     */
    @Test
    public void policyPaymentTest() {
        // TODO: test policyPayment
    }

    /**
     * Test the property 'policyShipping'
     */
    @Test
    public void policyShippingTest() {
        // TODO: test policyShipping
    }

    /**
     * Test the property 'policyRefunds'
     */
    @Test
    public void policyRefundsTest() {
        // TODO: test policyRefunds
    }

    /**
     * Test the property 'policyAdditional'
     */
    @Test
    public void policyAdditionalTest() {
        // TODO: test policyAdditional
    }

    /**
     * Test the property 'policySellerInfo'
     */
    @Test
    public void policySellerInfoTest() {
        // TODO: test policySellerInfo
    }

    /**
     * Test the property 'policyUpdateDate'
     */
    @Test
    public void policyUpdateDateTest() {
        // TODO: test policyUpdateDate
    }

    /**
     * Test the property 'policyHasPrivateReceiptInfo'
     */
    @Test
    public void policyHasPrivateReceiptInfoTest() {
        // TODO: test policyHasPrivateReceiptInfo
    }

    /**
     * Test the property 'hasUnstructuredPolicies'
     */
    @Test
    public void hasUnstructuredPoliciesTest() {
        // TODO: test hasUnstructuredPolicies
    }

    /**
     * Test the property 'policyPrivacy'
     */
    @Test
    public void policyPrivacyTest() {
        // TODO: test policyPrivacy
    }

    /**
     * Test the property 'vacationAutoreply'
     */
    @Test
    public void vacationAutoreplyTest() {
        // TODO: test vacationAutoreply
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'imageUrl760x100'
     */
    @Test
    public void imageUrl760x100Test() {
        // TODO: test imageUrl760x100
    }

    /**
     * Test the property 'numFavorers'
     */
    @Test
    public void numFavorersTest() {
        // TODO: test numFavorers
    }

    /**
     * Test the property 'languages'
     */
    @Test
    public void languagesTest() {
        // TODO: test languages
    }

    /**
     * Test the property 'iconUrlFullxfull'
     */
    @Test
    public void iconUrlFullxfullTest() {
        // TODO: test iconUrlFullxfull
    }

    /**
     * Test the property 'isUsingStructuredPolicies'
     */
    @Test
    public void isUsingStructuredPoliciesTest() {
        // TODO: test isUsingStructuredPolicies
    }

    /**
     * Test the property 'hasOnboardedStructuredPolicies'
     */
    @Test
    public void hasOnboardedStructuredPoliciesTest() {
        // TODO: test hasOnboardedStructuredPolicies
    }

    /**
     * Test the property 'includeDisputeFormLink'
     */
    @Test
    public void includeDisputeFormLinkTest() {
        // TODO: test includeDisputeFormLink
    }

    /**
     * Test the property 'isDirectCheckoutOnboarded'
     */
    @Test
    public void isDirectCheckoutOnboardedTest() {
        // TODO: test isDirectCheckoutOnboarded
    }

    /**
     * Test the property 'isEtsyPaymentsOnboarded'
     */
    @Test
    public void isEtsyPaymentsOnboardedTest() {
        // TODO: test isEtsyPaymentsOnboarded
    }

    /**
     * Test the property 'isCalculatedEligible'
     */
    @Test
    public void isCalculatedEligibleTest() {
        // TODO: test isCalculatedEligible
    }

    /**
     * Test the property 'isOptedInToBuyerPromise'
     */
    @Test
    public void isOptedInToBuyerPromiseTest() {
        // TODO: test isOptedInToBuyerPromise
    }

    /**
     * Test the property 'isShopUsBased'
     */
    @Test
    public void isShopUsBasedTest() {
        // TODO: test isShopUsBased
    }

    /**
     * Test the property 'transactionSoldCount'
     */
    @Test
    public void transactionSoldCountTest() {
        // TODO: test transactionSoldCount
    }

    /**
     * Test the property 'shippingFromCountryIso'
     */
    @Test
    public void shippingFromCountryIsoTest() {
        // TODO: test shippingFromCountryIso
    }

    /**
     * Test the property 'shopLocationCountryIso'
     */
    @Test
    public void shopLocationCountryIsoTest() {
        // TODO: test shopLocationCountryIso
    }

    /**
     * Test the property 'reviewCount'
     */
    @Test
    public void reviewCountTest() {
        // TODO: test reviewCount
    }

    /**
     * Test the property 'reviewAverage'
     */
    @Test
    public void reviewAverageTest() {
        // TODO: test reviewAverage
    }

}
