/*
 * Etsy Open API v3
 * <div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy's Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2023 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: developers@etsy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * A representation of structured data values.
 */
@ApiModel(description = "A representation of structured data values.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-08T08:37:51.285-04:00[America/Toronto]")
public class ListingPropertyValue {
  public static final String SERIALIZED_NAME_PROPERTY_ID = "property_id";
  @SerializedName(SERIALIZED_NAME_PROPERTY_ID)
  private Long propertyId;

  public static final String SERIALIZED_NAME_PROPERTY_NAME = "property_name";
  @SerializedName(SERIALIZED_NAME_PROPERTY_NAME)
  private String propertyName;

  public static final String SERIALIZED_NAME_SCALE_ID = "scale_id";
  @SerializedName(SERIALIZED_NAME_SCALE_ID)
  private Long scaleId;

  public static final String SERIALIZED_NAME_SCALE_NAME = "scale_name";
  @SerializedName(SERIALIZED_NAME_SCALE_NAME)
  private String scaleName;

  public static final String SERIALIZED_NAME_VALUE_IDS = "value_ids";
  @SerializedName(SERIALIZED_NAME_VALUE_IDS)
  private List<Long> valueIds = null;

  public static final String SERIALIZED_NAME_VALUES = "values";
  @SerializedName(SERIALIZED_NAME_VALUES)
  private List<String> values = null;

  public ListingPropertyValue() { 
  }

  public ListingPropertyValue propertyId(Long propertyId) {
    
    this.propertyId = propertyId;
    return this;
  }

   /**
   * The numeric ID of the Property.
   * minimum: 1
   * @return propertyId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The numeric ID of the Property.")

  public Long getPropertyId() {
    return propertyId;
  }


  public void setPropertyId(Long propertyId) {
    this.propertyId = propertyId;
  }


  public ListingPropertyValue propertyName(String propertyName) {
    
    this.propertyName = propertyName;
    return this;
  }

   /**
   * The name of the Property.
   * @return propertyName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the Property.")

  public String getPropertyName() {
    return propertyName;
  }


  public void setPropertyName(String propertyName) {
    this.propertyName = propertyName;
  }


  public ListingPropertyValue scaleId(Long scaleId) {
    
    this.scaleId = scaleId;
    return this;
  }

   /**
   * The numeric ID of the scale (if any).
   * minimum: 1
   * @return scaleId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The numeric ID of the scale (if any).")

  public Long getScaleId() {
    return scaleId;
  }


  public void setScaleId(Long scaleId) {
    this.scaleId = scaleId;
  }


  public ListingPropertyValue scaleName(String scaleName) {
    
    this.scaleName = scaleName;
    return this;
  }

   /**
   * The label used to describe the chosen scale (if any).
   * @return scaleName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The label used to describe the chosen scale (if any).")

  public String getScaleName() {
    return scaleName;
  }


  public void setScaleName(String scaleName) {
    this.scaleName = scaleName;
  }


  public ListingPropertyValue valueIds(List<Long> valueIds) {
    
    this.valueIds = valueIds;
    return this;
  }

  public ListingPropertyValue addValueIdsItem(Long valueIdsItem) {
    if (this.valueIds == null) {
      this.valueIds = new ArrayList<Long>();
    }
    this.valueIds.add(valueIdsItem);
    return this;
  }

   /**
   * The numeric IDs of the Property values
   * @return valueIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The numeric IDs of the Property values")

  public List<Long> getValueIds() {
    return valueIds;
  }


  public void setValueIds(List<Long> valueIds) {
    this.valueIds = valueIds;
  }


  public ListingPropertyValue values(List<String> values) {
    
    this.values = values;
    return this;
  }

  public ListingPropertyValue addValuesItem(String valuesItem) {
    if (this.values == null) {
      this.values = new ArrayList<String>();
    }
    this.values.add(valuesItem);
    return this;
  }

   /**
   * The Property values
   * @return values
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The Property values")

  public List<String> getValues() {
    return values;
  }


  public void setValues(List<String> values) {
    this.values = values;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListingPropertyValue listingPropertyValue = (ListingPropertyValue) o;
    return Objects.equals(this.propertyId, listingPropertyValue.propertyId) &&
        Objects.equals(this.propertyName, listingPropertyValue.propertyName) &&
        Objects.equals(this.scaleId, listingPropertyValue.scaleId) &&
        Objects.equals(this.scaleName, listingPropertyValue.scaleName) &&
        Objects.equals(this.valueIds, listingPropertyValue.valueIds) &&
        Objects.equals(this.values, listingPropertyValue.values);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(propertyId, propertyName, scaleId, scaleName, valueIds, values);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListingPropertyValue {\n");
    sb.append("    propertyId: ").append(toIndentedString(propertyId)).append("\n");
    sb.append("    propertyName: ").append(toIndentedString(propertyName)).append("\n");
    sb.append("    scaleId: ").append(toIndentedString(scaleId)).append("\n");
    sb.append("    scaleName: ").append(toIndentedString(scaleName)).append("\n");
    sb.append("    valueIds: ").append(toIndentedString(valueIds)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

