/*
 * Etsy Open API v3
 * <div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy's Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2023 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: developers@etsy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * A section within a shop, into which a user can sort listings.
 */
@ApiModel(description = "A section within a shop, into which a user can sort listings.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-08T08:37:51.285-04:00[America/Toronto]")
public class ShopSection {
  public static final String SERIALIZED_NAME_SHOP_SECTION_ID = "shop_section_id";
  @SerializedName(SERIALIZED_NAME_SHOP_SECTION_ID)
  private Long shopSectionId;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_RANK = "rank";
  @SerializedName(SERIALIZED_NAME_RANK)
  private Long rank;

  public static final String SERIALIZED_NAME_USER_ID = "user_id";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private Long userId;

  public static final String SERIALIZED_NAME_ACTIVE_LISTING_COUNT = "active_listing_count";
  @SerializedName(SERIALIZED_NAME_ACTIVE_LISTING_COUNT)
  private Long activeListingCount;

  public ShopSection() { 
  }

  public ShopSection shopSectionId(Long shopSectionId) {
    
    this.shopSectionId = shopSectionId;
    return this;
  }

   /**
   * The numeric ID of a section in a specific Etsy shop.
   * minimum: 1
   * @return shopSectionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The numeric ID of a section in a specific Etsy shop.")

  public Long getShopSectionId() {
    return shopSectionId;
  }


  public void setShopSectionId(Long shopSectionId) {
    this.shopSectionId = shopSectionId;
  }


  public ShopSection title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * The title string for a shop section.
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The title string for a shop section.")

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public ShopSection rank(Long rank) {
    
    this.rank = rank;
    return this;
  }

   /**
   * The positive non-zero numeric position of this section in the section display order for a shop, with rank 1 sections appearing first.
   * minimum: 0
   * @return rank
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The positive non-zero numeric position of this section in the section display order for a shop, with rank 1 sections appearing first.")

  public Long getRank() {
    return rank;
  }


  public void setRank(Long rank) {
    this.rank = rank;
  }


  public ShopSection userId(Long userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * The numeric ID of the [user](/documentation/reference#tag/User) who owns this shop section.
   * minimum: 1
   * @return userId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The numeric ID of the [user](/documentation/reference#tag/User) who owns this shop section.")

  public Long getUserId() {
    return userId;
  }


  public void setUserId(Long userId) {
    this.userId = userId;
  }


  public ShopSection activeListingCount(Long activeListingCount) {
    
    this.activeListingCount = activeListingCount;
    return this;
  }

   /**
   * The number of active listings in one section of a specific Etsy shop.
   * minimum: 0
   * @return activeListingCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of active listings in one section of a specific Etsy shop.")

  public Long getActiveListingCount() {
    return activeListingCount;
  }


  public void setActiveListingCount(Long activeListingCount) {
    this.activeListingCount = activeListingCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShopSection shopSection = (ShopSection) o;
    return Objects.equals(this.shopSectionId, shopSection.shopSectionId) &&
        Objects.equals(this.title, shopSection.title) &&
        Objects.equals(this.rank, shopSection.rank) &&
        Objects.equals(this.userId, shopSection.userId) &&
        Objects.equals(this.activeListingCount, shopSection.activeListingCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shopSectionId, title, rank, userId, activeListingCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShopSection {\n");
    sb.append("    shopSectionId: ").append(toIndentedString(shopSectionId)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    rank: ").append(toIndentedString(rank)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    activeListingCount: ").append(toIndentedString(activeListingCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

