/*
 * Etsy Open API v3
 * <div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace <a class=\"wt-text-link wt-p-xs-0\" href=\"https://www.etsy.com/developers/documentation\">Etsy's Open API v2</a>, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/issues/new/choose\">please add an issue in Github</a>.</p></div>&copy; 2021-2022 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: developers@etsy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The record of one shipment event for a ShopReceipt. A receipt may have many ShopReceiptShipment records.
 */
@ApiModel(description = "The record of one shipment event for a ShopReceipt. A receipt may have many ShopReceiptShipment records.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-04-08T15:52:16.342-04:00[America/Toronto]")
public class ShopReceiptShipment {
  public static final String SERIALIZED_NAME_RECEIPT_SHIPPING_ID = "receipt_shipping_id";
  @SerializedName(SERIALIZED_NAME_RECEIPT_SHIPPING_ID)
  private Integer receiptShippingId;

  public static final String SERIALIZED_NAME_SHIPMENT_NOTIFICATION_TIMESTAMP = "shipment_notification_timestamp";
  @SerializedName(SERIALIZED_NAME_SHIPMENT_NOTIFICATION_TIMESTAMP)
  private Integer shipmentNotificationTimestamp;

  public static final String SERIALIZED_NAME_CARRIER_NAME = "carrier_name";
  @SerializedName(SERIALIZED_NAME_CARRIER_NAME)
  private String carrierName;

  public static final String SERIALIZED_NAME_TRACKING_CODE = "tracking_code";
  @SerializedName(SERIALIZED_NAME_TRACKING_CODE)
  private String trackingCode;

  public ShopReceiptShipment() { 
  }

  public ShopReceiptShipment receiptShippingId(Integer receiptShippingId) {
    
    this.receiptShippingId = receiptShippingId;
    return this;
  }

   /**
   * The unique numeric ID of a Shop Receipt Shipment record.
   * minimum: 1
   * @return receiptShippingId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "The unique numeric ID of a Shop Receipt Shipment record.")

  public Integer getReceiptShippingId() {
    return receiptShippingId;
  }


  public void setReceiptShippingId(Integer receiptShippingId) {
    this.receiptShippingId = receiptShippingId;
  }


  public ShopReceiptShipment shipmentNotificationTimestamp(Integer shipmentNotificationTimestamp) {
    
    this.shipmentNotificationTimestamp = shipmentNotificationTimestamp;
    return this;
  }

   /**
   * The time at which Etsy notified the buyer of the shipment event, in epoch seconds.
   * minimum: 946684800
   * @return shipmentNotificationTimestamp
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The time at which Etsy notified the buyer of the shipment event, in epoch seconds.")

  public Integer getShipmentNotificationTimestamp() {
    return shipmentNotificationTimestamp;
  }


  public void setShipmentNotificationTimestamp(Integer shipmentNotificationTimestamp) {
    this.shipmentNotificationTimestamp = shipmentNotificationTimestamp;
  }


  public ShopReceiptShipment carrierName(String carrierName) {
    
    this.carrierName = carrierName;
    return this;
  }

   /**
   * The name string for the carrier/company responsible for delivering the shipment.
   * @return carrierName
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The name string for the carrier/company responsible for delivering the shipment.")

  public String getCarrierName() {
    return carrierName;
  }


  public void setCarrierName(String carrierName) {
    this.carrierName = carrierName;
  }


  public ShopReceiptShipment trackingCode(String trackingCode) {
    
    this.trackingCode = trackingCode;
    return this;
  }

   /**
   * The tracking code string provided by the carrier/company for the shipment.
   * @return trackingCode
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The tracking code string provided by the carrier/company for the shipment.")

  public String getTrackingCode() {
    return trackingCode;
  }


  public void setTrackingCode(String trackingCode) {
    this.trackingCode = trackingCode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShopReceiptShipment shopReceiptShipment = (ShopReceiptShipment) o;
    return Objects.equals(this.receiptShippingId, shopReceiptShipment.receiptShippingId) &&
        Objects.equals(this.shipmentNotificationTimestamp, shopReceiptShipment.shipmentNotificationTimestamp) &&
        Objects.equals(this.carrierName, shopReceiptShipment.carrierName) &&
        Objects.equals(this.trackingCode, shopReceiptShipment.trackingCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(receiptShippingId, shipmentNotificationTimestamp, carrierName, trackingCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShopReceiptShipment {\n");
    sb.append("    receiptShippingId: ").append(toIndentedString(receiptShippingId)).append("\n");
    sb.append("    shipmentNotificationTimestamp: ").append(toIndentedString(shipmentNotificationTimestamp)).append("\n");
    sb.append("    carrierName: ").append(toIndentedString(carrierName)).append("\n");
    sb.append("    trackingCode: ").append(toIndentedString(trackingCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

