/*
 * Etsy Open API v3
 * <div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy's Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2023 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: developers@etsy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.Money;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * The refund record for a receipt.
 */
@ApiModel(description = "The refund record for a receipt.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-08T08:37:51.285-04:00[America/Toronto]")
public class ShopRefund {
  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  private Money amount;

  public static final String SERIALIZED_NAME_CREATED_TIMESTAMP = "created_timestamp";
  @SerializedName(SERIALIZED_NAME_CREATED_TIMESTAMP)
  private Long createdTimestamp;

  public static final String SERIALIZED_NAME_REASON = "reason";
  @SerializedName(SERIALIZED_NAME_REASON)
  private String reason;

  public static final String SERIALIZED_NAME_NOTE_FROM_ISSUER = "note_from_issuer";
  @SerializedName(SERIALIZED_NAME_NOTE_FROM_ISSUER)
  private String noteFromIssuer;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public ShopRefund() { 
  }

  public ShopRefund amount(Money amount) {
    
    this.amount = amount;
    return this;
  }

   /**
   * A number equal to the refund total.
   * @return amount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A number equal to the refund total.")

  public Money getAmount() {
    return amount;
  }


  public void setAmount(Money amount) {
    this.amount = amount;
  }


  public ShopRefund createdTimestamp(Long createdTimestamp) {
    
    this.createdTimestamp = createdTimestamp;
    return this;
  }

   /**
   * The date &amp; time of the refund, in epoch seconds.
   * minimum: 946684800
   * @return createdTimestamp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date & time of the refund, in epoch seconds.")

  public Long getCreatedTimestamp() {
    return createdTimestamp;
  }


  public void setCreatedTimestamp(Long createdTimestamp) {
    this.createdTimestamp = createdTimestamp;
  }


  public ShopRefund reason(String reason) {
    
    this.reason = reason;
    return this;
  }

   /**
   * The reason string given for the refund.
   * @return reason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The reason string given for the refund.")

  public String getReason() {
    return reason;
  }


  public void setReason(String reason) {
    this.reason = reason;
  }


  public ShopRefund noteFromIssuer(String noteFromIssuer) {
    
    this.noteFromIssuer = noteFromIssuer;
    return this;
  }

   /**
   * The note string created by the refund issuer.
   * @return noteFromIssuer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The note string created by the refund issuer.")

  public String getNoteFromIssuer() {
    return noteFromIssuer;
  }


  public void setNoteFromIssuer(String noteFromIssuer) {
    this.noteFromIssuer = noteFromIssuer;
  }


  public ShopRefund status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * The status indication string for the refund.
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The status indication string for the refund.")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShopRefund shopRefund = (ShopRefund) o;
    return Objects.equals(this.amount, shopRefund.amount) &&
        Objects.equals(this.createdTimestamp, shopRefund.createdTimestamp) &&
        Objects.equals(this.reason, shopRefund.reason) &&
        Objects.equals(this.noteFromIssuer, shopRefund.noteFromIssuer) &&
        Objects.equals(this.status, shopRefund.status);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, createdTimestamp, reason, noteFromIssuer, status);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShopRefund {\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    createdTimestamp: ").append(toIndentedString(createdTimestamp)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    noteFromIssuer: ").append(toIndentedString(noteFromIssuer)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

