/*
 * Etsy Open API v3
 * <div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy's Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2023 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: developers@etsy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * A list of variations chosen by the buyer during checkout.
 */
@ApiModel(description = "A list of variations chosen by the buyer during checkout.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-08T08:37:51.285-04:00[America/Toronto]")
public class TransactionVariations {
  public static final String SERIALIZED_NAME_PROPERTY_ID = "property_id";
  @SerializedName(SERIALIZED_NAME_PROPERTY_ID)
  private Long propertyId;

  public static final String SERIALIZED_NAME_VALUE_ID = "value_id";
  @SerializedName(SERIALIZED_NAME_VALUE_ID)
  private Long valueId;

  public static final String SERIALIZED_NAME_FORMATTED_NAME = "formatted_name";
  @SerializedName(SERIALIZED_NAME_FORMATTED_NAME)
  private String formattedName;

  public static final String SERIALIZED_NAME_FORMATTED_VALUE = "formatted_value";
  @SerializedName(SERIALIZED_NAME_FORMATTED_VALUE)
  private String formattedValue;

  public TransactionVariations() { 
  }

  public TransactionVariations propertyId(Long propertyId) {
    
    this.propertyId = propertyId;
    return this;
  }

   /**
   * The variation property ID.
   * @return propertyId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The variation property ID.")

  public Long getPropertyId() {
    return propertyId;
  }


  public void setPropertyId(Long propertyId) {
    this.propertyId = propertyId;
  }


  public TransactionVariations valueId(Long valueId) {
    
    this.valueId = valueId;
    return this;
  }

   /**
   * The ID of the variation value selected.
   * @return valueId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the variation value selected.")

  public Long getValueId() {
    return valueId;
  }


  public void setValueId(Long valueId) {
    this.valueId = valueId;
  }


  public TransactionVariations formattedName(String formattedName) {
    
    this.formattedName = formattedName;
    return this;
  }

   /**
   * Formatted name of the variation.
   * @return formattedName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Formatted name of the variation.")

  public String getFormattedName() {
    return formattedName;
  }


  public void setFormattedName(String formattedName) {
    this.formattedName = formattedName;
  }


  public TransactionVariations formattedValue(String formattedValue) {
    
    this.formattedValue = formattedValue;
    return this;
  }

   /**
   * Value of the variation entered by the buyer.
   * @return formattedValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Value of the variation entered by the buyer.")

  public String getFormattedValue() {
    return formattedValue;
  }


  public void setFormattedValue(String formattedValue) {
    this.formattedValue = formattedValue;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionVariations transactionVariations = (TransactionVariations) o;
    return Objects.equals(this.propertyId, transactionVariations.propertyId) &&
        Objects.equals(this.valueId, transactionVariations.valueId) &&
        Objects.equals(this.formattedName, transactionVariations.formattedName) &&
        Objects.equals(this.formattedValue, transactionVariations.formattedValue);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(propertyId, valueId, formattedName, formattedValue);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionVariations {\n");
    sb.append("    propertyId: ").append(toIndentedString(propertyId)).append("\n");
    sb.append("    valueId: ").append(toIndentedString(valueId)).append("\n");
    sb.append("    formattedName: ").append(toIndentedString(formattedName)).append("\n");
    sb.append("    formattedValue: ").append(toIndentedString(formattedValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

