/*
 * Etsy Open API v3
 * <div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace <a class=\"wt-text-link wt-p-xs-0\" href=\"https://www.etsy.com/developers/documentation\">Etsy's Open API v2</a>, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/issues/new/choose\">please add an issue in Github</a>.</p></div>&copy; 2021-2022 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: developers@etsy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * A transaction review record left by a User.
 */
@ApiModel(description = "A transaction review record left by a User.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-04-08T15:52:16.342-04:00[America/Toronto]")
public class TransactionReview {
  public static final String SERIALIZED_NAME_SHOP_ID = "shop_id";
  @SerializedName(SERIALIZED_NAME_SHOP_ID)
  private Integer shopId;

  public static final String SERIALIZED_NAME_LISTING_ID = "listing_id";
  @SerializedName(SERIALIZED_NAME_LISTING_ID)
  private Integer listingId;

  public static final String SERIALIZED_NAME_TRANSACTION_ID = "transaction_id";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_ID)
  private Integer transactionId;

  public static final String SERIALIZED_NAME_BUYER_USER_ID = "buyer_user_id";
  @SerializedName(SERIALIZED_NAME_BUYER_USER_ID)
  private Integer buyerUserId;

  public static final String SERIALIZED_NAME_RATING = "rating";
  @SerializedName(SERIALIZED_NAME_RATING)
  private Integer rating;

  public static final String SERIALIZED_NAME_REVIEW = "review";
  @SerializedName(SERIALIZED_NAME_REVIEW)
  private String review;

  public static final String SERIALIZED_NAME_LANGUAGE = "language";
  @SerializedName(SERIALIZED_NAME_LANGUAGE)
  private String language;

  public static final String SERIALIZED_NAME_IMAGE_URL_FULLXFULL = "image_url_fullxfull";
  @SerializedName(SERIALIZED_NAME_IMAGE_URL_FULLXFULL)
  private String imageUrlFullxfull;

  public static final String SERIALIZED_NAME_CREATE_TIMESTAMP = "create_timestamp";
  @SerializedName(SERIALIZED_NAME_CREATE_TIMESTAMP)
  private Integer createTimestamp;

  public static final String SERIALIZED_NAME_UPDATE_TIMESTAMP = "update_timestamp";
  @SerializedName(SERIALIZED_NAME_UPDATE_TIMESTAMP)
  private Integer updateTimestamp;

  public TransactionReview() { 
  }

  public TransactionReview shopId(Integer shopId) {
    
    this.shopId = shopId;
    return this;
  }

   /**
   * The shop&#39;s numeric ID.
   * minimum: 1
   * @return shopId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The shop's numeric ID.")

  public Integer getShopId() {
    return shopId;
  }


  public void setShopId(Integer shopId) {
    this.shopId = shopId;
  }


  public TransactionReview listingId(Integer listingId) {
    
    this.listingId = listingId;
    return this;
  }

   /**
   * The ID of the ShopListing that the TransactionReview belongs to.
   * minimum: 1
   * @return listingId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The ID of the ShopListing that the TransactionReview belongs to.")

  public Integer getListingId() {
    return listingId;
  }


  public void setListingId(Integer listingId) {
    this.listingId = listingId;
  }


  public TransactionReview transactionId(Integer transactionId) {
    
    this.transactionId = transactionId;
    return this;
  }

   /**
   * The ID of the ShopReceipt Transaction that the TransactionReview belongs to.
   * minimum: 1
   * @return transactionId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The ID of the ShopReceipt Transaction that the TransactionReview belongs to.")

  public Integer getTransactionId() {
    return transactionId;
  }


  public void setTransactionId(Integer transactionId) {
    this.transactionId = transactionId;
  }


  public TransactionReview buyerUserId(Integer buyerUserId) {
    
    this.buyerUserId = buyerUserId;
    return this;
  }

   /**
   * The numeric ID of the user who was the buyer in this transaction. Note: This field may be absent, depending on the buyer&#39;s privacy settings.
   * minimum: 1
   * @return buyerUserId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "The numeric ID of the user who was the buyer in this transaction. Note: This field may be absent, depending on the buyer's privacy settings.")

  public Integer getBuyerUserId() {
    return buyerUserId;
  }


  public void setBuyerUserId(Integer buyerUserId) {
    this.buyerUserId = buyerUserId;
  }


  public TransactionReview rating(Integer rating) {
    
    this.rating = rating;
    return this;
  }

   /**
   * Rating value on scale from 1 to 5
   * minimum: 1
   * maximum: 5
   * @return rating
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Rating value on scale from 1 to 5")

  public Integer getRating() {
    return rating;
  }


  public void setRating(Integer rating) {
    this.rating = rating;
  }


  public TransactionReview review(String review) {
    
    this.review = review;
    return this;
  }

   /**
   * A message left by the author, explaining the feedback, if provided.
   * @return review
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "A message left by the author, explaining the feedback, if provided.")

  public String getReview() {
    return review;
  }


  public void setReview(String review) {
    this.review = review;
  }


  public TransactionReview language(String language) {
    
    this.language = language;
    return this;
  }

   /**
   * The language of the TransactionReview
   * @return language
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The language of the TransactionReview")

  public String getLanguage() {
    return language;
  }


  public void setLanguage(String language) {
    this.language = language;
  }


  public TransactionReview imageUrlFullxfull(String imageUrlFullxfull) {
    
    this.imageUrlFullxfull = imageUrlFullxfull;
    return this;
  }

   /**
   * The url to a photo provided with the feedback, dimensions fullxfull. Note: This field may be absent, depending on the buyer&#39;s privacy settings.
   * @return imageUrlFullxfull
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "The url to a photo provided with the feedback, dimensions fullxfull. Note: This field may be absent, depending on the buyer's privacy settings.")

  public String getImageUrlFullxfull() {
    return imageUrlFullxfull;
  }


  public void setImageUrlFullxfull(String imageUrlFullxfull) {
    this.imageUrlFullxfull = imageUrlFullxfull;
  }


  public TransactionReview createTimestamp(Integer createTimestamp) {
    
    this.createTimestamp = createTimestamp;
    return this;
  }

   /**
   * The date and time the TransactionReview was created in epoch seconds.
   * minimum: 946684800
   * @return createTimestamp
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The date and time the TransactionReview was created in epoch seconds.")

  public Integer getCreateTimestamp() {
    return createTimestamp;
  }


  public void setCreateTimestamp(Integer createTimestamp) {
    this.createTimestamp = createTimestamp;
  }


  public TransactionReview updateTimestamp(Integer updateTimestamp) {
    
    this.updateTimestamp = updateTimestamp;
    return this;
  }

   /**
   * The date and time the TransactionReview was updated in epoch seconds.
   * minimum: 946684800
   * @return updateTimestamp
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The date and time the TransactionReview was updated in epoch seconds.")

  public Integer getUpdateTimestamp() {
    return updateTimestamp;
  }


  public void setUpdateTimestamp(Integer updateTimestamp) {
    this.updateTimestamp = updateTimestamp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionReview transactionReview = (TransactionReview) o;
    return Objects.equals(this.shopId, transactionReview.shopId) &&
        Objects.equals(this.listingId, transactionReview.listingId) &&
        Objects.equals(this.transactionId, transactionReview.transactionId) &&
        Objects.equals(this.buyerUserId, transactionReview.buyerUserId) &&
        Objects.equals(this.rating, transactionReview.rating) &&
        Objects.equals(this.review, transactionReview.review) &&
        Objects.equals(this.language, transactionReview.language) &&
        Objects.equals(this.imageUrlFullxfull, transactionReview.imageUrlFullxfull) &&
        Objects.equals(this.createTimestamp, transactionReview.createTimestamp) &&
        Objects.equals(this.updateTimestamp, transactionReview.updateTimestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shopId, listingId, transactionId, buyerUserId, rating, review, language, imageUrlFullxfull, createTimestamp, updateTimestamp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionReview {\n");
    sb.append("    shopId: ").append(toIndentedString(shopId)).append("\n");
    sb.append("    listingId: ").append(toIndentedString(listingId)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    buyerUserId: ").append(toIndentedString(buyerUserId)).append("\n");
    sb.append("    rating: ").append(toIndentedString(rating)).append("\n");
    sb.append("    review: ").append(toIndentedString(review)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    imageUrlFullxfull: ").append(toIndentedString(imageUrlFullxfull)).append("\n");
    sb.append("    createTimestamp: ").append(toIndentedString(createTimestamp)).append("\n");
    sb.append("    updateTimestamp: ").append(toIndentedString(updateTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

