/*
 * Etsy Open API v3
 * <div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy's Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2023 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: developers@etsy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.V3ApplicationListingsListingIdInventoryOfferings;
import org.openapitools.client.model.V3ApplicationListingsListingIdInventoryPropertyValues;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * V3ApplicationListingsListingIdInventoryProducts
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-08T08:37:51.285-04:00[America/Toronto]")
public class V3ApplicationListingsListingIdInventoryProducts {
  public static final String SERIALIZED_NAME_SKU = "sku";
  @SerializedName(SERIALIZED_NAME_SKU)
  private String sku;

  public static final String SERIALIZED_NAME_PROPERTY_VALUES = "property_values";
  @SerializedName(SERIALIZED_NAME_PROPERTY_VALUES)
  private List<V3ApplicationListingsListingIdInventoryPropertyValues> propertyValues = null;

  public static final String SERIALIZED_NAME_OFFERINGS = "offerings";
  @SerializedName(SERIALIZED_NAME_OFFERINGS)
  private List<V3ApplicationListingsListingIdInventoryOfferings> offerings = new ArrayList<V3ApplicationListingsListingIdInventoryOfferings>();

  public V3ApplicationListingsListingIdInventoryProducts() { 
  }

  public V3ApplicationListingsListingIdInventoryProducts sku(String sku) {
    
    this.sku = sku;
    return this;
  }

   /**
   * The SKU string for the product
   * @return sku
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The SKU string for the product")

  public String getSku() {
    return sku;
  }


  public void setSku(String sku) {
    this.sku = sku;
  }


  public V3ApplicationListingsListingIdInventoryProducts propertyValues(List<V3ApplicationListingsListingIdInventoryPropertyValues> propertyValues) {
    
    this.propertyValues = propertyValues;
    return this;
  }

  public V3ApplicationListingsListingIdInventoryProducts addPropertyValuesItem(V3ApplicationListingsListingIdInventoryPropertyValues propertyValuesItem) {
    if (this.propertyValues == null) {
      this.propertyValues = new ArrayList<V3ApplicationListingsListingIdInventoryPropertyValues>();
    }
    this.propertyValues.add(propertyValuesItem);
    return this;
  }

   /**
   * A list of property value entries for this product. Note: parenthesis characters (&#x60;(&#x60; and &#x60;)&#x60;) are not allowed.
   * @return propertyValues
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of property value entries for this product. Note: parenthesis characters (`(` and `)`) are not allowed.")

  public List<V3ApplicationListingsListingIdInventoryPropertyValues> getPropertyValues() {
    return propertyValues;
  }


  public void setPropertyValues(List<V3ApplicationListingsListingIdInventoryPropertyValues> propertyValues) {
    this.propertyValues = propertyValues;
  }


  public V3ApplicationListingsListingIdInventoryProducts offerings(List<V3ApplicationListingsListingIdInventoryOfferings> offerings) {
    
    this.offerings = offerings;
    return this;
  }

  public V3ApplicationListingsListingIdInventoryProducts addOfferingsItem(V3ApplicationListingsListingIdInventoryOfferings offeringsItem) {
    this.offerings.add(offeringsItem);
    return this;
  }

   /**
   * A list of product offering entries for this product.
   * @return offerings
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "A list of product offering entries for this product.")

  public List<V3ApplicationListingsListingIdInventoryOfferings> getOfferings() {
    return offerings;
  }


  public void setOfferings(List<V3ApplicationListingsListingIdInventoryOfferings> offerings) {
    this.offerings = offerings;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V3ApplicationListingsListingIdInventoryProducts v3ApplicationListingsListingIdInventoryProducts = (V3ApplicationListingsListingIdInventoryProducts) o;
    return Objects.equals(this.sku, v3ApplicationListingsListingIdInventoryProducts.sku) &&
        Objects.equals(this.propertyValues, v3ApplicationListingsListingIdInventoryProducts.propertyValues) &&
        Objects.equals(this.offerings, v3ApplicationListingsListingIdInventoryProducts.offerings);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(sku, propertyValues, offerings);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V3ApplicationListingsListingIdInventoryProducts {\n");
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("    propertyValues: ").append(toIndentedString(propertyValues)).append("\n");
    sb.append("    offerings: ").append(toIndentedString(offerings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

